#!/usr/bin/python3


def raise_exception():
    a = 10
    b = "2"
    result = a / b
    print(result)
